service: serverless-ci-cd-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage}
  environment: ${file(env.yml):${self:provider.stage}}
  region: ${file(env.yml):${self:provider.stage}.AWS_REGION}

functions:
  index:
    handler: src/functions/index.handler
