on:
  workflow_dispatch:
  push:
    branches: [ "develop", "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [ "20.x" ]
    
    steps:
      - uses: actions/checkout@v4
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'yarn'

      # - name: Build sharp layer
      #   run: | 
      #     npm --prefix ./layers/sharp_layer/nodejs/node20 \
      #       install --cpu=x64 --os=linux --libc=glibc sharp

      # - name: Install dependencies
      #   run: yarn install --production --frozen-lockfile

      - name: Setup environment variables
        run: |
          touch env.yml
          echo "${{ secrets.ENV_FILE }}" > env.yml
          cat env.yml
      
      - name: Show event
        run: echo "${{ toJSON(github) }}"
      - name: Run migrations
        if: contains(github.event.head_commit.message, '[run-migrations=true]')
        run: echo "Run migrations"

  

